hh-ia.a.2 hh-ia.a.8 and hh-ia.a.9 added
inspire-eu-validation/ets-repository pull request #827
Opened 2024-04-17 13:43 UTC by dperezBM

Corresponding issue: [#1046](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1046)

2024-04-19 10:42 UTC, fabiovinci requested changes
Hi @dperezBM,

I put a comment inline that should be verified before merging.
Thanks

2024-04-19 10:42 UTC, fabiovinci commented on data-hh/hh-ia/ets-hh-ia-bsxets.xml
> +									<label>hh-ia.a.4: EnvHealthDeterminantTypeValue</label>
Is this codelist verified for the new feature types too?

EnvHealthDeterminantTypeValue <a name="EnvHealthDeterminantTypeValue"></a> | //schema-element(hh:EnvHealthDeterminantMeasure)/hh:type/@xlink:href <br> //schema-element(hh:**EnvHealthDeterminantConcentrationMeasure**)/hh:type/@xlink:href <br> //schema-element(hh:**EnvHealthDeterminantNoiseMeasure**)/hh:type/@xlink:href <br> //schema-element(hh:EnvHealthDeterminantStatisticalData)/hh:type/@xlink:href | 1 | No

2024-04-23 10:41 UTC, dperezBM commented on data-hh/hh-ia/ets-hh-ia-bsxets.xml
> +									<label>hh-ia.a.4: EnvHealthDeterminantTypeValue</label>
I have just performed a new commit with your change so I think that the PR would take it into account when it is approved.
Could you check it again?
 https://github.com/inspire-eu-validation/ets-repository/pull/827/files

2024-04-23 10:57 UTC, fabiovinci approved these changes

2024-04-23 10:57 UTC, fabiovinci commented on data-hh/hh-ia/ets-hh-ia-bsxets.xml
> +									<label>hh-ia.a.4: EnvHealthDeterminantTypeValue</label>
It seems ok now.

2024-05-06 21:03 UTC, merged